; Noctalia Monochrome - pink accent from noctalia palette

[Monochrome]
accent             = f5c2e7
accent-active      = f5c2e7
accent-inactive    = 1e1e1e
banner             = f5c2e7
border-active      = 333333
border-inactive    = f5c2e7
header             = 535353
highlight          = 999999
main               = 000000
notification       = f5c2e7
notification-error = e22134
subtext            = b3b3b3
text               = FFFFFF
