palette = "noctalia"
add_newline = false

format = "$directory$git_branch$git_status$character"
right_format = "$cmd_duration$battery$directory$python$nodejs$rust$golang$lua$time"

scan_timeout = 100
truncation_length = 40

[character]
success_symbol = "[❯](bold mauve)"
error_symbol = "[❯](bold flamingo)"

[os]
disabled = false
style = "bold mauve"
format = "[$name ]($style)"

[os.symbols]
CachyOS = "  "

[directory]
style = "bold mauve"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 🔒"

[git_branch]
symbol = " "
style = "bold mauve"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold yellow"
format = "[$all_status$ahead_behind]($style) "
untracked = "?"
modified = "+"
staged = "●"

[cmd_duration]
min_time = 3000
style = "italic subtext0"
format = "[ $duration]($style) "

[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
format = "[$symbol $percentage]($style) "
display_threshold = 20

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 100
style = "italic subtext0"

[time]
disabled = false
time_format = "%R"
style = "bold subtext1"
format = "[ $time]($style)"

[python]
symbol = " "
style = "bold peach"
format = "[$symbol$version]($style) "
only_files = true

[nodejs]
symbol = " "
style = "bold teal"
format = "[$symbol$version]($style) "
only_files = true

[rust]
symbol = " "
style = "bold flamingo"
format = "[$symbol$version]($style) "
only_files = true

[golang]
symbol = " "
style = "bold sky"
format = "[$symbol$version]($style) "
only_files = true

[lua]
symbol = " "
style = "bold sapphire"
format = "[$symbol$version]($style) "
only_files = true

[package]
symbol = "   "
style = "bold subtext0"
format = "[$symbol$version]($style) "

[aws]
symbol = " "
style = "bold subtext0"
format = "[$symbol$profile]($style) "

[fill]
symbol = " "

[env_var]
symbol = " "

[nix_shell]
symbol = " "

[container]
symbol = " "

[status]
format = "[$symbol$common_meaning]($style) "
map_symbol = true
disabled = false

[status.symbol]
success = ""
error = "✗"

[status.style]
success = "bold green"
error = "bold red"

[palettes.noctalia]
blue      = "#e2e2e2"
red       = "#ffb4ab"
green     = "#ffffff"
yellow    = "#c6c6c6"
cyan      = "#ababab"
magenta   = "#7d7d7d"
white     = "#e2e2e2"
black     = "#474747"
rosewater = "#c6c6c6"
flamingo  = "#ffb4ab"
pink      = "#7d7d7d"
mauve     = "#7d7d7d"
maroon    = "#ffb4ab"
peach     = "#c6c6c6"
teal      = "#ababab"
sky       = "#ababab"
sapphire  = "#e2e2e2"
lavender  = "#7d7d7d"
text      = "#e2e2e2"
subtext1  = "#e2e2e2"
subtext0  = "#919191"
overlay2  = "#919191"
overlay1  = "#919191"
overlay0  = "#474747"
surface2  = "#474747"
surface1  = "#474747"
surface0  = "#131313"
base      = "#131313"
mantle    = "#131313"
crust     = "#131313"
